sudo: required
dist: trusty
language: generic
os:
  - osx
  - linux
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install qt5 p7zip qbs; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew link --force qt5; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo "deb http://pkg.mxe.cc/repos/apt/debian wheezy main" |sudo tee --append /etc/apt/sources.list; fi

  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -y install qt58declarative qt58quickcontrols qt58quickcontrols2 qt58graphicaleffects qt58tools qt58svg mesa-common-dev libglu1-mesa-dev qt58qbs gcc-5 g++-5 nodejs; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH=/opt/qt58/bin:$PATH; fi

  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then MXE_PREFIX="mxe-i686-w64-mingw32.static"; sudo apt-get -y --force-yes install $MXE_PREFIX-qtdeclarative $MXE_PREFIX-qtquickcontrols $MXE_PREFIX-qtquickcontrols2 $MXE_PREFIX-qtgraphicaleffects $MXE_PREFIX-qttools $MXE_PREFIX-qtsvg; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then qbs setup-toolchains --type mingw /usr/lib/mxe/usr/bin/i686-w64-mingw32.static-gcc i686-w64-mingw32-static; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then qbs setup-qt /usr/lib/mxe/usr/i686-w64-mingw32.static/qt5/bin/qmake qt5-mxe; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then qbs config profiles.qt5-mxe.baseProfile i686-w64-mingw32-static; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sed -i 's/parent.parent.qtModuleName/product.moduleProperty(product.moduleName, "qtModuleName")/g'  ~/.config/QtProject/qbs/$(qbs --version)/profiles/qt5-mxe/modules/Qt/QtPlugin.qbs; fi

  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5; fi
  - qbs setup-toolchains --detect

  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then qbs setup-qt /opt/qt58/bin/qmake qt5; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then qbs config profiles.qt5.baseProfile gcc; fi

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then qbs setup-qt /usr/local/opt/qt5/bin/qmake qt5; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then qbs config profiles.qt5.baseProfile xcode-macosx-x86_64; fi
  - qbs config defaultProfile qt5

script:
  - ./configure
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./tools/deploy_win.sh QuarkShell qt5-mxe; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./tools/deploy_linux.sh QuarkShell qt5; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./tools/deploy_mac.sh QuarkShell qt5; fi
  - ls .
deploy:
  - provider: releases
    prerelease: true
    api_key:
      secure: IckXTW+tOTID4xV9tc1arkNlJPNA7gUfziDbWyjuqxgmIdrMJthpT6BSzhaCb3+yFqXDDuNn73li4SJz0Xy6jvQXLK+Jgsl3iyOButiyq7X61bxeA0fd9Kc5Y3P7lVQbYPvaczIRT0NOBPwmRjPZr1bvIESS/jnVvBF0uM+jIilJAMDYVBcSr0jZz0JJLs9eBTBZiH6lH1FD1NWhBpYpYA0P39O39nofZOGvZRdRgZ97pxBRGhVhjy5LwysDnza78ik92lQSBb1PcItM4wm9gt6eEBjgvP/rfl5JHn0ST5226Me98Ppq88hJ5sCZRXdmWg30CJ4WrTg/NCEp/bZXx8m2iKSA0QCei9Et8nnlSSYzrMGfTCvGbFLKWb027rcNsbohkfUTV8BKooPPSx/24t3lN6J3baYLD4ilDwkBAGouKti4+qLkT5BipxTOeBIW6Ot/SW7kv7ivnqrLsCzNHrtlqawURmaOSot4Noz0j4ZyuH1jbML3NsqNBCWZDsTsnLCkXYz05zPF+xtXxIUR8X6SKILWMp531aIhU/hhOcl8ajBp4ri+JQwTIqqXfkBidzfTI+d94EWukDclEa4YDqAO8FLLVv1cIwZH3PrqWH8dRrOxdUZTB+dTohJkkwufoMAvy83AoE1T3gpdd8JNdRJP+h6jC3HTCQLFw3gmkpA=
    file: $TRAVIS_BUILD_DIR/dist/win/quark-shell-win-x86.zip
    skip_cleanup: true
    on:
      tags: true
      repo: freemountain/quark
      condition: $TRAVIS_OS_NAME = linux
  - provider: releases
    prerelease: true
    api_key:
      secure: IckXTW+tOTID4xV9tc1arkNlJPNA7gUfziDbWyjuqxgmIdrMJthpT6BSzhaCb3+yFqXDDuNn73li4SJz0Xy6jvQXLK+Jgsl3iyOButiyq7X61bxeA0fd9Kc5Y3P7lVQbYPvaczIRT0NOBPwmRjPZr1bvIESS/jnVvBF0uM+jIilJAMDYVBcSr0jZz0JJLs9eBTBZiH6lH1FD1NWhBpYpYA0P39O39nofZOGvZRdRgZ97pxBRGhVhjy5LwysDnza78ik92lQSBb1PcItM4wm9gt6eEBjgvP/rfl5JHn0ST5226Me98Ppq88hJ5sCZRXdmWg30CJ4WrTg/NCEp/bZXx8m2iKSA0QCei9Et8nnlSSYzrMGfTCvGbFLKWb027rcNsbohkfUTV8BKooPPSx/24t3lN6J3baYLD4ilDwkBAGouKti4+qLkT5BipxTOeBIW6Ot/SW7kv7ivnqrLsCzNHrtlqawURmaOSot4Noz0j4ZyuH1jbML3NsqNBCWZDsTsnLCkXYz05zPF+xtXxIUR8X6SKILWMp531aIhU/hhOcl8ajBp4ri+JQwTIqqXfkBidzfTI+d94EWukDclEa4YDqAO8FLLVv1cIwZH3PrqWH8dRrOxdUZTB+dTohJkkwufoMAvy83AoE1T3gpdd8JNdRJP+h6jC3HTCQLFw3gmkpA=
    file: $TRAVIS_BUILD_DIR/dist/linux/quark-shell-linux-x86_64.zip
    skip_cleanup: true
    on:
      tags: true
      repo: freemountain/quark
      condition: $TRAVIS_OS_NAME = linux
  - provider: releases
    prerelease: true
    api_key:
      secure: IckXTW+tOTID4xV9tc1arkNlJPNA7gUfziDbWyjuqxgmIdrMJthpT6BSzhaCb3+yFqXDDuNn73li4SJz0Xy6jvQXLK+Jgsl3iyOButiyq7X61bxeA0fd9Kc5Y3P7lVQbYPvaczIRT0NOBPwmRjPZr1bvIESS/jnVvBF0uM+jIilJAMDYVBcSr0jZz0JJLs9eBTBZiH6lH1FD1NWhBpYpYA0P39O39nofZOGvZRdRgZ97pxBRGhVhjy5LwysDnza78ik92lQSBb1PcItM4wm9gt6eEBjgvP/rfl5JHn0ST5226Me98Ppq88hJ5sCZRXdmWg30CJ4WrTg/NCEp/bZXx8m2iKSA0QCei9Et8nnlSSYzrMGfTCvGbFLKWb027rcNsbohkfUTV8BKooPPSx/24t3lN6J3baYLD4ilDwkBAGouKti4+qLkT5BipxTOeBIW6Ot/SW7kv7ivnqrLsCzNHrtlqawURmaOSot4Noz0j4ZyuH1jbML3NsqNBCWZDsTsnLCkXYz05zPF+xtXxIUR8X6SKILWMp531aIhU/hhOcl8ajBp4ri+JQwTIqqXfkBidzfTI+d94EWukDclEa4YDqAO8FLLVv1cIwZH3PrqWH8dRrOxdUZTB+dTohJkkwufoMAvy83AoE1T3gpdd8JNdRJP+h6jC3HTCQLFw3gmkpA=
    file: $TRAVIS_BUILD_DIR/dist/linux/quark-shell-x86_64.AppImage
    skip_cleanup: true
    on:
      tags: true
      repo: freemountain/quark
      condition: $TRAVIS_OS_NAME = linux
  - provider: releases
    prerelease: true
    api_key:
      secure: IckXTW+tOTID4xV9tc1arkNlJPNA7gUfziDbWyjuqxgmIdrMJthpT6BSzhaCb3+yFqXDDuNn73li4SJz0Xy6jvQXLK+Jgsl3iyOButiyq7X61bxeA0fd9Kc5Y3P7lVQbYPvaczIRT0NOBPwmRjPZr1bvIESS/jnVvBF0uM+jIilJAMDYVBcSr0jZz0JJLs9eBTBZiH6lH1FD1NWhBpYpYA0P39O39nofZOGvZRdRgZ97pxBRGhVhjy5LwysDnza78ik92lQSBb1PcItM4wm9gt6eEBjgvP/rfl5JHn0ST5226Me98Ppq88hJ5sCZRXdmWg30CJ4WrTg/NCEp/bZXx8m2iKSA0QCei9Et8nnlSSYzrMGfTCvGbFLKWb027rcNsbohkfUTV8BKooPPSx/24t3lN6J3baYLD4ilDwkBAGouKti4+qLkT5BipxTOeBIW6Ot/SW7kv7ivnqrLsCzNHrtlqawURmaOSot4Noz0j4ZyuH1jbML3NsqNBCWZDsTsnLCkXYz05zPF+xtXxIUR8X6SKILWMp531aIhU/hhOcl8ajBp4ri+JQwTIqqXfkBidzfTI+d94EWukDclEa4YDqAO8FLLVv1cIwZH3PrqWH8dRrOxdUZTB+dTohJkkwufoMAvy83AoE1T3gpdd8JNdRJP+h6jC3HTCQLFw3gmkpA=
    file: $TRAVIS_BUILD_DIR/dist/mac/quark-shell-mac-x86_64.zip
    skip_cleanup: true
    on:
      tags: true
      repo: freemountain/quark
      condition: $TRAVIS_OS_NAME = osx
