sudo: required
dist: xenial
language: generic

install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt57-xenial
  - sudo apt-get update
  - sudo apt-get -y install qt57declarative qt57quickcontrols qt57quickcontrols2 qt57graphicaleffects qt57tools qt57svg
  - sudo apt-get -y install mesa-common-dev libglu1-mesa-dev patchelf
  - sudo apt-get -y install xvfb

script:
  - source /opt/qt57/bin/qt57-env.sh
  - ./tools/bootstrap.sh
  - mkdir build && cd build && qmake .. && make && cd ..
  - ./tools/deploy_linux.sh build/quark
