sudo: required
dist: trusty
language: generic
os:
  - linux

script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install qt5; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew link --force qt5; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:beineri/opt-qt57-trusty; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -y install qt57declarative qt57quickcontrols qt57quickcontrols2 qt57graphicaleffects qt57tools qt57svg mesa-common-dev libglu1-mesa-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH=/opt/qt57/bin:$PATH; fi
  - cd tools && make bootstrap && cd ..
  - mkdir build && cd build && qmake .. && make && make clean
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ../tools/deploy_linux.sh quark; fi
  - if [ "$TRAVIS_OS_NAME" == "owx" ]; then ../tools/deploy_mac.sh quark.app; fi
  - ls .

deploy:
  - provider: releases
    api_key:
      secure: IckXTW+tOTID4xV9tc1arkNlJPNA7gUfziDbWyjuqxgmIdrMJthpT6BSzhaCb3+yFqXDDuNn73li4SJz0Xy6jvQXLK+Jgsl3iyOButiyq7X61bxeA0fd9Kc5Y3P7lVQbYPvaczIRT0NOBPwmRjPZr1bvIESS/jnVvBF0uM+jIilJAMDYVBcSr0jZz0JJLs9eBTBZiH6lH1FD1NWhBpYpYA0P39O39nofZOGvZRdRgZ97pxBRGhVhjy5LwysDnza78ik92lQSBb1PcItM4wm9gt6eEBjgvP/rfl5JHn0ST5226Me98Ppq88hJ5sCZRXdmWg30CJ4WrTg/NCEp/bZXx8m2iKSA0QCei9Et8nnlSSYzrMGfTCvGbFLKWb027rcNsbohkfUTV8BKooPPSx/24t3lN6J3baYLD4ilDwkBAGouKti4+qLkT5BipxTOeBIW6Ot/SW7kv7ivnqrLsCzNHrtlqawURmaOSot4Noz0j4ZyuH1jbML3NsqNBCWZDsTsnLCkXYz05zPF+xtXxIUR8X6SKILWMp531aIhU/hhOcl8ajBp4ri+JQwTIqqXfkBidzfTI+d94EWukDclEa4YDqAO8FLLVv1cIwZH3PrqWH8dRrOxdUZTB+dTohJkkwufoMAvy83AoE1T3gpdd8JNdRJP+h6jC3HTCQLFw3gmkpA=
    file: /home/travis/build/freemountain/quark/build/Quark-x86_64.AppImage
    skip_cleanup: true
    on:
      repo: freemountain/quark
      condition: $TRAVIS_OS_NAME = linux
  - provider: releases
    api_key:
      secure: IckXTW+tOTID4xV9tc1arkNlJPNA7gUfziDbWyjuqxgmIdrMJthpT6BSzhaCb3+yFqXDDuNn73li4SJz0Xy6jvQXLK+Jgsl3iyOButiyq7X61bxeA0fd9Kc5Y3P7lVQbYPvaczIRT0NOBPwmRjPZr1bvIESS/jnVvBF0uM+jIilJAMDYVBcSr0jZz0JJLs9eBTBZiH6lH1FD1NWhBpYpYA0P39O39nofZOGvZRdRgZ97pxBRGhVhjy5LwysDnza78ik92lQSBb1PcItM4wm9gt6eEBjgvP/rfl5JHn0ST5226Me98Ppq88hJ5sCZRXdmWg30CJ4WrTg/NCEp/bZXx8m2iKSA0QCei9Et8nnlSSYzrMGfTCvGbFLKWb027rcNsbohkfUTV8BKooPPSx/24t3lN6J3baYLD4ilDwkBAGouKti4+qLkT5BipxTOeBIW6Ot/SW7kv7ivnqrLsCzNHrtlqawURmaOSot4Noz0j4ZyuH1jbML3NsqNBCWZDsTsnLCkXYz05zPF+xtXxIUR8X6SKILWMp531aIhU/hhOcl8ajBp4ri+JQwTIqqXfkBidzfTI+d94EWukDclEa4YDqAO8FLLVv1cIwZH3PrqWH8dRrOxdUZTB+dTohJkkwufoMAvy83AoE1T3gpdd8JNdRJP+h6jC3HTCQLFw3gmkpA=
    file: /home/travis/build/freemountain/quark/build/quark.app
    skip_cleanup: true
    on:
      repo: freemountain/quark
      condition: $TRAVIS_OS_NAME = osx
