init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
  - set QTDIR=C:\Qt\5.7\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin
build_script:
  - dir
  - bash -lc "mingw32-make bootstrap && mingw32-make test && cd .."
  - bash -lc "mkdir build && cd build && qmake .. && mingw32-make && ../tools/deploy_win.sh release/quark.exe"
  - bash -lc "cd build && mv release quark && rm -rf quark/*.o quark/*.cpp && 7z a quark-windows-x86.zip quark && ls && echo $APPVEYOR_BUILD_FOLDER"
  - dir
artifacts:
  - path: build/quark-windows-x86.zip
    name: quark-windows-x86
deploy:
  provider: GitHub
  auth_token:
    secure: u5Kpbjsb3snNA8/9K8ETWWSl8lYVPZTvXX+FlGAKTXFazOqsNAxPgk1pceOyev+S
  draft: false
  force_update: false
  prerelease: false
  on:
    appveyor_repo_tag: true
on_finish:
  - ps: $blockRdp = $false; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
