init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
  - set QTDIR=C:\Qt\5.7\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin
build_script:
  - dir
  - bash: -lc ">-
      mkdir build; \
      cd build; \
      ./../configure --qt=/c/Qt/5.7/mingw53_32/bin; \
      mingw32-make -j4; \
      mingw32-make clean-build; \
      mingw32-make package; \
      mv release quark; \
      7z a quark-windows-x86.zip quark;"
- dir
artifacts:
  - path: build/quark-windows-x86.zip
    name: quark-windows-x86
deploy:
  provider: GitHub
  auth_token:
    secure: u5Kpbjsb3snNA8/9K8ETWWSl8lYVPZTvXX+FlGAKTXFazOqsNAxPgk1pceOyev+S
  draft: false
  force_update: false
  prerelease: false
  on:
    appveyor_repo_tag: true
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
