init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
  - set QTDIR=C:\Qt\5.7\mingw53_32
  - set PATH=C:\msys64\bin%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%
build_script:
  - bash -x tools/appveyor.sh
artifacts:
  - path: build/quark-windows-x86.zip
    name: quark-windows-x86
deploy:
  provider: GitHub
  auth_token:
    secure: u5Kpbjsb3snNA8/9K8ETWWSl8lYVPZTvXX+FlGAKTXFazOqsNAxPgk1pceOyev+S
  draft: false
  force_update: false
  prerelease: false
  on:
    appveyor_repo_tag: true
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
