#!/bin/sh
set -e

PROJECT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

OS="$($PROJECT_PATH/tools/uname.sh -o)"
ARCH="$($PROJECT_PATH/tools/uname.sh -a)"

BIN_PATH="$PROJECT_PATH/tmp/bin-$OS-$ARCH"
BUILD_PATH="$PWD"


print_vars() {
  echo "QT_PATH = ${QT_PATH}"
  echo "OS = ${OS}"
  echo "ARCH = ${ARCH}"
  echo "BUILD_PATH = ${BUILD_PATH}"
}

for i in "$@"
do
case $i in
    -q=*|--qt=*)
    QT_PATH="${i#*=}"
    shift # past argument=value
    ;;
    *)
    echo "Unkonw option: $i";
    print_vars
    exit 1
    ;;
esac
done

if [ -z "$QT_PATH" ]; then
  echo "qt path is missing"
  exit 1
fi

echo "PROJECT_PATH:=$PROJECT_PATH" > Makefile
echo "QT:=$QT_PATH" >> Makefile

cat "$PROJECT_PATH/Makefile.default" >> Makefile
make bootstrap -j4

$QT_PATH/qmake -o qmake.mk $PROJECT_PATH
